const products = [
    {
        id: 1,
        title: "Cable USB-C a Lightning Neon",
        description: "Cable trenzado de alta resistencia con luces de neón. Perfecto para cargar tu iPhone con estilo y durabilidad. 1 metro de largo.",
        price: 8500,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-1.png", "assets/products/placeholder-2.png"],
        stock: 25,
        featured: true,
        tags: ["cable", "usb-c", "lightning", "iphone", "neon"]
    },
    {
        id: 2,
        title: "Cargador Rápido GaN 65W",
        description: "Cargador de pared ultra compacto con tecnología GaN. Dos puertos USB-C y un puerto USB-A para cargar todos tus dispositivos a máxima velocidad.",
        price: 22000,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-3.png"],
        stock: 15,
        featured: true,
        tags: ["cargador", "gan", "rapido", "usb-c", "laptop"]
    },
    {
        id: 3,
        title: "Auriculares In-Ear Pro",
        description: "Sonido de alta fidelidad con cancelación de ruido activa. Diseño ergonómico y batería de hasta 24 horas con el estuche de carga.",
        price: 45000,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-1.png"],
        stock: 10,
        featured: false,
        tags: ["auriculares", "audio", "in-ear", "bluetooth", "cancelacion de ruido"]
    },
    {
        id: 4,
        title: "Mousepad Gamer XXL Glow",
        description: "Superficie de microfibra optimizada para control y velocidad. Bordes con iluminación RGB personalizable.",
        price: 18000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-2.png"],
        stock: 30,
        featured: false,
        tags: ["mousepad", "gamer", "rgb", "accesorio"]
    },
    {
        id: 5,
        title: "Cable HDMI 2.1 8K",
        description: "Cable de ultra alta velocidad para resoluciones 8K a 60Hz o 4K a 120Hz. Conectores bañados en oro para máxima conductividad.",
        price: 11500,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-3.png"],
        stock: 18,
        featured: false,
        tags: ["cable", "hdmi", "8k", "video", "gaming"]
    },
    {
        id: 6,
        title: "Hub USB-C 7-en-1",
        description: "Expande tus puertos con este hub de aluminio. Incluye HDMI 4K, lector de tarjetas SD/microSD, 3x USB 3.0 y carga Power Delivery.",
        price: 29000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-1.png"],
        stock: 12,
        featured: true,
        tags: ["hub", "usb-c", "adaptador", "accesorio"]
    },
    {
        id: 7,
        title: "Cargador Inalámbrico Magnético",
        description: "Carga inalámbrica compatible con MagSafe. Diseño minimalista y un imán potente para una alineación perfecta siempre.",
        price: 15000,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-2.png"],
        stock: 22,
        featured: false,
        tags: ["cargador", "inalambrico", "magsafe", "iphone"]
    },
    {
        id: 8,
        title: "Parlante Bluetooth Portátil",
        description: "Sonido potente y claro en un formato compacto. Resistente al agua (IPX7) y 12 horas de batería. Conexión Bluetooth 5.2.",
        price: 32000,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-3.png"],
        stock: 8,
        featured: false,
        tags: ["parlante", "bluetooth", "portatil", "audio", "waterproof"]
    },
    {
        id: 9,
        title: "Teclado Mecánico TKL RGB",
        description: "Formato Tenkeyless (sin pad numérico) para más espacio. Switches Brown, keycaps de PBT y retroiluminación RGB personalizable.",
        price: 55000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-1.png"],
        stock: 7,
        featured: true,
        tags: ["teclado", "mecanico", "tkl", "rgb", "gamer"]
    },
    {
        id: 10,
        title: "Cable USB-C a USB-C 100W",
        description: "Cable de silicona ultra flexible para cargar laptops, tablets y teléfonos a máxima velocidad. Soporta hasta 100W de Power Delivery.",
        price: 9800,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-2.png"],
        stock: 40,
        featured: false,
        tags: ["cable", "usb-c", "100w", "pd", "laptop"]
    },
    {
        id: 11,
        title: "Power Bank 20000mAh",
        description: "Batería externa de gran capacidad para múltiples cargas. Salida rápida de 22.5W y pantalla digital para ver el nivel de carga.",
        price: 25500,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-3.png"],
        stock: 0,
        featured: false,
        tags: ["power bank", "bateria", "cargador", "portatil"]
    },
    {
        id: 12,
        title: "Micrófono USB para Streaming",
        description: "Micrófono de condensador con patrón cardioide. Calidad de estudio para streaming, podcasting y grabaciones. Plug and play.",
        price: 38000,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-1.png"],
        stock: 11,
        featured: false,
        tags: ["microfono", "usb", "streaming", "podcast", "audio"]
    },
    {
        id: 13,
        title: "Soporte para Auriculares RGB",
        description: "Base robusta con iluminación RGB dinámica y 2 puertos USB adicionales para carga.",
        price: 12500,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-2.png"],
        stock: 20,
        featured: false,
        tags: ["soporte", "auriculares", "rgb", "gamer"]
    },
    {
        id: 14,
        title: "Webcam Full HD 1080p",
        description: "Cámara web con anillo de luz integrado y micrófono con reducción de ruido. Ideal para streaming y videollamadas.",
        price: 28000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-1.png"],
        stock: 15,
        featured: true,
        tags: ["webcam", "streaming", "1080p", "video"]
    },
    {
        id: 15,
        title: "Cable Micro-USB Trenzado",
        description: "Cable de nylon trenzado de alta durabilidad. 2 metros de largo. Compatible con dispositivos Android y periféricos.",
        price: 4500,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-3.png"],
        stock: 50,
        featured: false,
        tags: ["cable", "micro-usb", "android", "carga"]
    },
    {
        id: 16,
        title: "Adaptador Bluetooth 5.0 USB",
        description: "Convierte tu PC o laptop sin Bluetooth en un dispositivo compatible. Conexión estable y bajo consumo.",
        price: 6500,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-2.png"],
        stock: 35,
        featured: false,
        tags: ["adaptador", "bluetooth", "usb", "dongle"]
    },
    {
        id: 17,
        title: "Cargador de Auto Carga Rápida",
        description: "Cargador dual USB-A y USB-C con tecnología QC 3.0 y PD. Carga tu celular mientras viajas.",
        price: 9800,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-1.png"],
        stock: 25,
        featured: false,
        tags: ["cargador", "auto", "usb-c", "viaje"]
    },
    {
        id: 18,
        title: "Barra de Sonido Compacta PC",
        description: "Soundbar estéreo con conexión USB y Jack 3.5mm. Diseño elegante que cabe debajo del monitor.",
        price: 19500,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-3.png"],
        stock: 12,
        featured: false,
        tags: ["parlante", "barra de sonido", "pc", "audio"]
    },
    {
        id: 19,
        title: "Kit de Limpieza 5 en 1",
        description: "Herramientas esenciales para limpiar teclados, auriculares y pantallas. Incluye cepillo, extractor de teclas y paño.",
        price: 3500,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-2.png"],
        stock: 60,
        featured: false,
        tags: ["limpieza", "kit", "teclado", "mantenimiento"]
    },
    {
        id: 20,
        title: "Micrófono Solapa Lavalier",
        description: "Micrófono omnidireccional con clip y cable de 1.5m. Conector 3.5mm TRRS para celulares y cámaras.",
        price: 8900,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-1.png"],
        stock: 18,
        featured: false,
        tags: ["microfono", "lavalier", "grabacion", "audio"]
    },
    {
        id: 21,
        title: "Cable Ethernet CAT8 2m",
        description: "Cable de red de ultra alta velocidad para gaming y streaming 4K. Blindaje SFTP contra interferencias.",
        price: 7200,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-3.png"],
        stock: 40,
        featured: false,
        tags: ["cable", "ethernet", "red", "internet", "cat8"]
    },
    {
        id: 22,
        title: "Funda Laptop 15.6 Impermeable",
        description: "Protección acolchada con interior de felpa suave. Tela exterior resistente al agua y bolsillos accesorios.",
        price: 14500,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-2.png"],
        stock: 22,
        featured: false,
        tags: ["funda", "laptop", "notebook", "proteccion"]
    },
    {
        id: 23,
        title: "Aro de Luz LED Escritorio",
        description: "Iluminación ajustable con trípode de mesa. 3 modos de color y 10 niveles de brillo. Alimentación USB.",
        price: 11000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-1.png"],
        stock: 30,
        featured: false,
        tags: ["aro de luz", "led", "streaming", "video"]
    },
    {
        id: 24,
        title: "Auriculares Gamer RGB 7.1",
        description: "Sonido envolvente virtual 7.1, micrófono flexible y luces RGB laterales. Almohadillas de espuma viscoelástica.",
        price: 38500,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-3.png"],
        stock: 14,
        featured: true,
        tags: ["auriculares", "gamer", "rgb", "7.1", "headset"]
    },
    {
        id: 25,
        title: "Base Refrigerante Notebook",
        description: "Soporte con 2 ventiladores silenciosos y altura ajustable. Mejora el rendimiento y ergonomía de tu laptop.",
        price: 16800,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-2.png"],
        stock: 16,
        featured: false,
        tags: ["cooler", "base", "notebook", "refrigeracion"]
    },
    {
        id: 26,
        title: "Cable DisplayPort 1.4",
        description: "Soporta resoluciones hasta 8K@60Hz y 4K@144Hz. Ideal para monitores gamer de alta tasa de refresco.",
        price: 10500,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-1.png"],
        stock: 28,
        featured: false,
        tags: ["cable", "displayport", "video", "monitor", "gamer"]
    },
    {
        id: 27,
        title: "Cargador Portátil Solar 10000mAh",
        description: "Power bank resistente a golpes y salpicaduras con panel solar de emergencia. Linterna LED integrada.",
        price: 29900,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-3.png"],
        stock: 10,
        featured: true,
        tags: ["power bank", "solar", "cargador", "outdoor"]
    }
];

window.products = products;