const products = [
    {
        id: 1,
        title: "Cable USB-C a Lightning Neon",
        description: "Cable trenzado de alta resistencia con luces de neón. Perfecto para cargar tu iPhone con estilo y durabilidad. 1 metro de largo.",
        price: 8500,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-1.png", "assets/products/placeholder-2.png"],
        stock: 25,
        featured: true,
        tags: ["cable", "usb-c", "lightning", "iphone", "neon"]
    },
    {
        id: 2,
        title: "Cargador Rápido GaN 65W",
        description: "Cargador de pared ultra compacto con tecnología GaN. Dos puertos USB-C y un puerto USB-A para cargar todos tus dispositivos a máxima velocidad.",
        price: 22000,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-3.png"],
        stock: 15,
        featured: true,
        tags: ["cargador", "gan", "rapido", "usb-c", "laptop"]
    },
    {
        id: 3,
        title: "Auriculares In-Ear Pro",
        description: "Sonido de alta fidelidad con cancelación de ruido activa. Diseño ergonómico y batería de hasta 24 horas con el estuche de carga.",
        price: 45000,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-1.png"],
        stock: 10,
        featured: false,
        tags: ["auriculares", "audio", "in-ear", "bluetooth", "cancelacion de ruido"]
    },
    {
        id: 4,
        title: "Mousepad Gamer XXL Glow",
        description: "Superficie de microfibra optimizada para control y velocidad. Bordes con iluminación RGB personalizable.",
        price: 18000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-2.png"],
        stock: 30,
        featured: false,
        tags: ["mousepad", "gamer", "rgb", "accesorio"]
    },
    {
        id: 5,
        title: "Cable HDMI 2.1 8K",
        description: "Cable de ultra alta velocidad para resoluciones 8K a 60Hz o 4K a 120Hz. Conectores bañados en oro para máxima conductividad.",
        price: 11500,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-3.png"],
        stock: 18,
        featured: false,
        tags: ["cable", "hdmi", "8k", "video", "gaming"]
    },
    {
        id: 6,
        title: "Hub USB-C 7-en-1",
        description: "Expande tus puertos con este hub de aluminio. Incluye HDMI 4K, lector de tarjetas SD/microSD, 3x USB 3.0 y carga Power Delivery.",
        price: 29000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-1.png"],
        stock: 12,
        featured: true,
        tags: ["hub", "usb-c", "adaptador", "accesorio"]
    },
    {
        id: 7,
        title: "Cargador Inalámbrico Magnético",
        description: "Carga inalámbrica compatible con MagSafe. Diseño minimalista y un imán potente para una alineación perfecta siempre.",
        price: 15000,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-2.png"],
        stock: 22,
        featured: false,
        tags: ["cargador", "inalambrico", "magsafe", "iphone"]
    },
    {
        id: 8,
        title: "Parlante Bluetooth Portátil",
        description: "Sonido potente y claro en un formato compacto. Resistente al agua (IPX7) y 12 horas de batería. Conexión Bluetooth 5.2.",
        price: 32000,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-3.png"],
        stock: 8,
        featured: false,
        tags: ["parlante", "bluetooth", "portatil", "audio", "waterproof"]
    },
    {
        id: 9,
        title: "Teclado Mecánico TKL RGB",
        description: "Formato Tenkeyless (sin pad numérico) para más espacio. Switches Brown, keycaps de PBT y retroiluminación RGB personalizable.",
        price: 55000,
        currency: "ARS",
        category: "Accesorios",
        images: ["assets/products/placeholder-1.png"],
        stock: 7,
        featured: true,
        tags: ["teclado", "mecanico", "tkl", "rgb", "gamer"]
    },
    {
        id: 10,
        title: "Cable USB-C a USB-C 100W",
        description: "Cable de silicona ultra flexible para cargar laptops, tablets y teléfonos a máxima velocidad. Soporta hasta 100W de Power Delivery.",
        price: 9800,
        currency: "ARS",
        category: "Cables",
        images: ["assets/products/placeholder-2.png"],
        stock: 40,
        featured: false,
        tags: ["cable", "usb-c", "100w", "pd", "laptop"]
    },
    {
        id: 11,
        title: "Power Bank 20000mAh",
        description: "Batería externa de gran capacidad para múltiples cargas. Salida rápida de 22.5W y pantalla digital para ver el nivel de carga.",
        price: 25500,
        currency: "ARS",
        category: "Cargadores",
        images: ["assets/products/placeholder-3.png"],
        stock: 0,
        featured: false,
        tags: ["power bank", "bateria", "cargador", "portatil"]
    },
    {
        id: 12,
        title: "Micrófono USB para Streaming",
        description: "Micrófono de condensador con patrón cardioide. Calidad de estudio para streaming, podcasting y grabaciones. Plug and play.",
        price: 38000,
        currency: "ARS",
        category: "Audio",
        images: ["assets/products/placeholder-1.png"],
        stock: 11,
        featured: false,
        tags: ["microfono", "usb", "streaming", "podcast", "audio"]
    }
];
